/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';
import { GroupProps } from '@react-three/fiber';
import { SkinnedMesh } from 'three';

export const FlyingGunman = (props: GroupProps) => {
  const group = useRef<any>();
  const { nodes, materials, animations } = useGLTF('/models/Robot Enemy Flying Gun.glb');
  // @ts-expect-error
  const { actions } = useAnimations(animations, group);

  const allNodes = nodes as Record<string, SkinnedMesh>;

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Root_Scene">
        <group name="RootNode">
          <group name="CharacterArmature" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <primitive object={allNodes.Root} />
          </group>
          <group
            name="Sphere001"
            position={[0, 0.471, 0.003]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <skinnedMesh
              name="Sphere001_1"
              geometry={allNodes.Sphere001_1.geometry}
              material={materials['Material.002']}
              skeleton={allNodes.Sphere001_1.skeleton}
            />
            <skinnedMesh
              name="Sphere001_2"
              geometry={allNodes.Sphere001_2.geometry}
              material={materials['Material.001']}
              skeleton={allNodes.Sphere001_2.skeleton}
            />
            <skinnedMesh
              name="Sphere001_3"
              geometry={allNodes.Sphere001_3.geometry}
              material={materials['Material.004']}
              skeleton={allNodes.Sphere001_3.skeleton}
            />
            <skinnedMesh
              name="Sphere001_4"
              geometry={allNodes.Sphere001_4.geometry}
              material={materials['Material.003']}
              skeleton={allNodes.Sphere001_4.skeleton}
            />
            <skinnedMesh
              name="Sphere001_5"
              geometry={allNodes.Sphere001_5.geometry}
              material={materials.Material}
              skeleton={allNodes.Sphere001_5.skeleton}
            />
            <skinnedMesh
              name="Sphere001_6"
              geometry={allNodes.Sphere001_6.geometry}
              material={materials.Grey}
              skeleton={allNodes.Sphere001_6.skeleton}
            />
            <skinnedMesh
              name="Sphere001_7"
              geometry={allNodes.Sphere001_7.geometry}
              material={materials.LightGrey}
              skeleton={allNodes.Sphere001_7.skeleton}
            />
          </group>
          <group
            name="Cube000"
            position={[0, 0.186, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <skinnedMesh
              name="Cube000_1"
              geometry={allNodes.Cube000_1.geometry}
              material={materials.Main2}
              skeleton={allNodes.Cube000_1.skeleton}
            />
            <skinnedMesh
              name="Cube000_2"
              geometry={allNodes.Cube000_2.geometry}
              material={materials.Edge}
              skeleton={allNodes.Cube000_2.skeleton}
            />
            <skinnedMesh
              name="Cube000_3"
              geometry={allNodes.Cube000_3.geometry}
              material={materials.Main}
              skeleton={allNodes.Cube000_3.skeleton}
            />
          </group>
        </group>
      </group>
    </group>
  );
};

useGLTF.preload('/models/Robot Enemy Flying Gun.glb');
