version: 2.1

defaults: &defaults
  working_directory: ~/service
  docker:
    - image: cimg/node:20.16.0

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run: yarn install --immutable
      - run: yarn build
      - save_cache:
          key: cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
            - ./src/apps/frontend/.next/cache
      - persist_to_workspace:
          root: ~/
          paths:
            - ./
  typecheck:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/
      - run:
          command: yarn typecheck
  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/
      - run:
          command: yarn test:ci
          environment:
            CIRCLE_BRANCH: local
            JEST_JUNIT_OUTPUT_DIR: ./junit.xml
      - store_artifacts:
          path: ./coverage

workflows:
  build-test-check:
    jobs:
      - build:
          name: build-dev
          context: dev
          filters:
            branches:
              ignore:
                - master
      - build:
          name: build-prod
          context: prod
          filters:
            branches:
              only:
                - master
      - typecheck:
          name: typecheck-dev
          context: dev
          filters:
            branches:
              ignore:
                - master
          requires:
            - build-dev
      - typecheck:
          name: typecheck-prod
          context: prod
          filters:
            branches:
              only:
                - master
          requires:
            - build-prod
      - test:
          name: test-dev
          context: dev
          filters:
            branches:
              ignore:
                - master
          requires:
            - build-dev
      - test:
          name: test-prod
          context: prod
          requires:
            - build-prod
          filters:
            branches:
              only:
                - master
