version: 2.1

defaults: &defaults
  working_directory: ~/service
  docker:
    - image: circleci/node:12.16.3

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run: yarn
      - run: yarn lint
      - run: yarn build
      - save_cache:
          key: cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
            - ./.next/cache
      - persist_to_workspace:
          root: ./
          paths:
            - ./
  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/
      - run:
          command: yarn test --runInBand --collectCoverage=true
          environment:
            CIRCLE_BRANCH: local
            JEST_JUNIT_OUTPUT_DIR: ./junit.xml
      - store_artifacts:
          path: ./coverage
  # deploy:
  #   <<: *defaults
  #   steps:
  #     - attach_workspace:
  #         at: ~/
  #     - run:
  #         command: yarn deploy
  #         no_output_timeout: 45m

workflows:
  build-test-deploy:
    jobs:
      - build:
          name: build-dev
          context: dev
      - build:
          name: build-prod
          context: prod
          filters:
            branches:
              only:
                - master
      - test:
          name: test-dev
          context: dev
          requires:
            - build-dev
      - test:
          name: test-prod
          context: prod
          requires:
            - build-prod
          filters:
            branches:
              only:
                - master
      # - deploy:
      #     name: deploy-dev
      #     context: dev
      #     requires:
      #       - aws-cli-dev
      #       - test-dev
      # - deploy:
      #     name: deploy-prod
      #     context: prod
      #     requires:
      #       - aws-cli-prod
      #       - test-prod
      #     filters:
      #       branches:
      #         only:
      #           - master